FROM gcc:latest

# Устанавливаем зависимости
RUN apt-get update && \
    apt-get install -y --no-install-recommends libasio-dev libpqxx-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Копируем файлы
COPY . .

# Собираем сервер. ВНИМАНИЕ: порядок флагов важен!
RUN g++ main.cpp -lpthread -lpqxx -o server

EXPOSE 8080

CMD ["./server"]